const mockRecipes = [
  {
    recipe_id: 3,
    api_id: 7980,
    recipe_title: "Greek Chickpeas with Spinach",
    summary: "A delicious meal that takes almost no time to whip up. Trader Joe's is the MVP here",
    source_url: "https://www.traderjoes.com/home",
    recipe_img: "https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=962&q=80",
  },
  {
    recipe_id: 4,
    api_id: 2534,
    recipe_title: "Tuna Melt",
    summary: "A healthy sandwich with no top slice of bread. Looks a little weird having to all be the same size....I wonder if there's Bootstrap responsiveness regarding this. Well, for tomorrow I guess!",
    source_url: "https://chickenofthesea.com/",
    recipe_img: "https://images.unsplash.com/photo-1606787366850-de6330128bfc?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxleHBsb3JlLWZlZWR8OHx8fGVufDB8fHx8&w=1000&q=80",
  },
  {
    recipe_id: 3,
    api_id: 7980,
    recipe_title: "Greek Chickpeas with Spinach",
    summary: "A delicious meal that takes almost no time to whip up. Trader Joe's is the MVP here",
    source_url: "https://www.traderjoes.com/home",
    recipe_img: "https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=962&q=80",
  },
  {
    recipe_id: 4,
    api_id: 2534,
    recipe_title: "Tuna Melt",
    summary: "A healthy sandwich with no top slice of bread",
    source_url: "https://chickenofthesea.com/",
    recipe_img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR7anyGwYY6pxp0hk4HuavSD6E9WwhhgwJAEuYPKUQ_gg&s",
  },
  {
    recipe_id: 3,
    api_id: 7980,
    recipe_title: "Greek Chickpeas with Spinach",
    summary: "A delicious meal that takes almost no time to whip up. Trader Joe's is the MVP here",
    source_url: "https://www.traderjoes.com/home",
    recipe_img: "https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=962&q=80",
  },
  {
    recipe_id: 4,
    api_id: 2534,
    recipe_title: "Tuna Melt",
    summary: "A healthy sandwich with no top slice of bread",
    source_url: "https://chickenofthesea.com/",
    recipe_img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR7anyGwYY6pxp0hk4HuavSD6E9WwhhgwJAEuYPKUQ_gg&s",
  },
  {
    recipe_id: 3,
    api_id: 7980,
    recipe_title: "Greek Chickpeas with Spinach",
    summary: "A delicious meal that takes almost no time to whip up. Trader Joe's is the MVP here",
    source_url: "https://www.traderjoes.com/home",
    recipe_img: "https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=962&q=80",
  },
  {
    recipe_id: 4,
    api_id: 2534,
    recipe_title: "Tuna Melt",
    summary: "A healthy sandwich with no top slice of bread",
    source_url: "https://chickenofthesea.com/",
    recipe_img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR7anyGwYY6pxp0hk4HuavSD6E9WwhhgwJAEuYPKUQ_gg&s",
  },
]

export default mockRecipes;